### PR TITLE
Spring cleaning documentation

### PR DESCRIPTION
**Pull request by gavinhenderson**
Hey Everyone 👋  

I have slightly spring cleaned the docs a little.

Changes:
- Made some the root documentation folder only contain docs
- Added a table of contents for the docs
- De-duped some content between contributing and onboard.
- I have added the NL Net milestone agreement (pending NL Net sign off)

This PR has a lot of green but none of the content was actually added, its just been moved.

Once this gets merged i'll delete the content from the wiki, its all in MD files now so the wiki will go stale.

Think the consensus for docs going forward is dev stuff goes into the docs folder on this repo and user facing stuff goes on the website.

### CODE REVIEW

**Comment by willwade** [comment]
Looks good to me. We have never really committed to using the wiki. Personally having all the docs in one place makes sense - wherever that be and I know @sjjhsjjh  has said it always makes more sense to put it directly in the repo. One thing - is that OnBoarding doc right in here though?  Is it really a dev thing?

**Comment by gavinhenderson** [comment]
@willwade Thats a good shout, ill shift it to the website 👍

**Comment by jcope** [comment]
Besides the deploy stages that failed... looks like there is an issue with submodules and captive-web-view? Not sure what changed though to trigger this.

All other updates to docs look good. 👍

**Comment by sjjhsjjh** [comment]
I prefer Markdown lists to be indented by four, whether the list is ordered or unordered. For example:

    -   This is an unordered list item.
        Pretend it wrapped to a second line like this.

    1.  This is an ordered list item.

Could this be adopted as part of the coding style please?

**Comment by sjjhsjjh** [comment]
> Besides the deploy stages that failed... looks like there is an issue with submodules and captive-web-view? Not sure what changed though to trigger this.

Hi Jeremy, Where is this issue visible please?

**Comment by sjjhsjjh** [comment]
The captive-web-view sub-module has somehow been added back in this branch. I think GitHub has some sort of bug in the area of merging and deleting files. I'll see if I can remove it from this branch.

**Review by sjjhsjjh — APPROVED** [review]

**Comment by willwade** [comment]
> > Besides the deploy stages that failed... looks like there is an issue with submodules and captive-web-view? Not sure what changed though to trigger this.
> 
> Hi Jeremy, Where is this issue visible please?

Looks like it’s sorted itself out. It’s only visible on the GitHub PR page Jim - at the bottom. Just travis and netlify builds.

**Comment by gavinhenderson** [comment]
@sjjhsjjh 

> I prefer Markdown lists to be indented by four, whether the list is ordered or unordered.

Do you mind if I leave the markdown as it is just now then we can have a separate PR to enforce all the rules we end up choosing for the style guide as well as some tooling so we don't have to manually apply the rules?


@willwade After looking the About page on the website has most of the content there so I don't think there is much use copying it over to the website as it would just be duplicated content. I think there is some value to have the context in the repo like it currently is.

**Comment by willwade** [comment]
> @willwade After looking the About page on the website has most of the content there so I don't think there is much use copying it over to the website as it would just be duplicated content. I think there is some value to have the context in the repo like it currently is.

Fine with me :)

**Pull request merged**
